import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios';
import World from './components/World';

export default function Home({data}) {
  console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<h1 className='text-gray-400'>hello there</h1>
<World data={data}/>
    </div>
  )
}

export async function getStaticProps(){


var options = {
  method: 'GET',
  url: 'https://vaccovid-coronavirus-vaccine-and-treatment-tracker.p.rapidapi.com/api/npm-covid-data/world',
  headers: {
    'x-rapidapi-host': 'vaccovid-coronavirus-vaccine-and-treatment-tracker.p.rapidapi.com',
    'x-rapidapi-key': 'aff1177afamsh1fb255402c24c5ap1be9e4jsn4efe400f2d7e'
  }
};

const res = await axios.request(options)

return {
  props:{
    data:res.data
  }
}
}